### ISSUE TITLE
index.js:1 videoElem.current.play() failed DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22 console.<computed> @ index.js:1 (anonymous) @ App.js:231

### ISSUE THREAD

**Issue by alejandrodavidmalavet** [videosdk-live/videosdk-rtc-react-sdk-example#12]
Occurs when I attempt to toggle my webcam. Video never appears and this error is logged

**Comment by alejandrodavidmalavet** [comment]
For context, this is on chrome with a macbook air M1

**Comment by arjun-kava** [comment]
Hey, Would you able to send us details of chrome version?

**Comment by alejandrodavidmalavet** [comment]
Version 101.0.4951.54 (Official Build) (arm64)

**Comment by ahmedbhesaniya97** [comment]
Hey @alejandrodavidmalavet ,
Please take a pull and let us know the same issue is generated or not.

**Comment by alejandrodavidmalavet** [comment]
Hi, the issue is still occurring

**Comment by alejandrodavidmalavet** [comment]
If it is any help, my video works fine in the joining screen but not within the meeting view

**Comment by rajansurani** [comment]
Hey, Do you toggle the webcam as soon as you join the meeting?

**Comment by alejandrodavidmalavet** [comment]
Yes. My webcam indicator turns on briefly when I press toggle, then it turns off and the error is displayed in the console.

**Comment by rajansurani** [comment]
Default behaviour is, once you join the meeting, webcam will auto start in a few second. When you click toggle webcam after join you are directing it to turn the webcam off.

**Comment by alejandrodavidmalavet** [comment]
To clarify, whether or not I press or do not press toggle, my video never works.

**Comment by ahmedbhesaniya97** [comment]
hey @alejandrodavidmalavet,
can you open this link and let us know the video is working or not.
https://videosdk.live/prebuilt/

**Comment by alejandrodavidmalavet** [comment]
@ahmedbhesaniya97 yes it works

**Comment by ahmedbhesaniya97** [comment]
Hey @alejandrodavidmalavet,
Please take a pull and check at your side.

**Comment by alejandrodavidmalavet** [comment]
Still not working. Here is the error log: 
```
log.js:24 [HMR] Waiting for update signal from WDS...
index.js:1 Warning: Received `true` for a non-boolean attribute `fullwidth`.

If you want to write it to the DOM, pass a string instead: fullwidth="true" or fullwidth={value.toString()}.
    at div
    at FormControl (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:10786:24)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at TextField (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:31312:28)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at MeetingDetailsScreen (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:2293:5)
    at div
    at Grid (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:12053:35)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at JoiningScreen (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1806:5)
    at App (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1442:83)
    at ThemeProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:177330:24)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
validateProperty$1 @ react-dom.development.js:3521
warnUnknownProperties @ react-dom.development.js:3559
validateProperties$2 @ react-dom.development.js:3583
validatePropertiesInDevelopment @ react-dom.development.js:8765
setInitialProperties @ react-dom.development.js:9041
finalizeInitialChildren @ react-dom.development.js:10201
completeWork @ react-dom.development.js:19470
completeUnitOfWork @ react-dom.development.js:22815
performUnitOfWork @ react-dom.development.js:22787
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.js:8
./src/index.js @ index.js:21
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ useResponsiveSize.js:37
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
webpackHotDevClient.js:138 ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning

(111:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning

(122:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning

(135:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning

(149:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Warning

(161:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:132 There were more warnings in other files.
You can find a complete log in the terminal.
printWarnings @ webpackHotDevClient.js:132
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
index.js:1 Warning: Invalid DOM property `autoplay`. Did you mean `autoPlay`?
    at video
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at div
    at Grid (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:12053:35)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at JoiningScreen (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1806:5)
    at App (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1442:83)
    at ThemeProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:177330:24)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
validateProperty$1 @ react-dom.development.js:3505
warnUnknownProperties @ react-dom.development.js:3559
validateProperties$2 @ react-dom.development.js:3583
validatePropertiesInDevelopment @ react-dom.development.js:8765
setInitialProperties @ react-dom.development.js:9041
finalizeInitialChildren @ react-dom.development.js:10201
completeWork @ react-dom.development.js:19470
completeUnitOfWork @ react-dom.development.js:22815
performUnitOfWork @ react-dom.development.js:22787
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
onClickCreateMeeting @ JoiningScreen.js:320
await in onClickCreateMeeting (async)
onClick @ MeetingDetailsScreen.js:40
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 Warning: Failed prop type: The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed.
    at Grid (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:12053:35)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at div
    at Grid (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:12053:35)
    at WithStyles (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178628:31)
    at div
    at StyledComponent (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:178399:28)
    at JoiningScreen (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1806:5)
    at App (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1442:83)
    at ThemeProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:177330:24)
console.<computed> @ index.js:1
printWarning @ react.development.js:220
error @ react.development.js:196
checkPropTypes @ react.development.js:1935
validatePropTypes @ react.development.js:2136
createElementWithValidation @ react.development.js:2240
WithStyles @ withStyles.js:79
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
onClickCreateMeeting @ JoiningScreen.js:320
await in onClickCreateMeeting (async)
onClick @ MeetingDetailsScreen.js:40
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ParticipantsView`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at ParticipantsView (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:761:82)
    at div
    at div
    at div
    at MeetingView (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1002:5)
    at MeetingProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:200049:23)
    at App (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1442:83)
    at ThemeProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:177330:24)
console.<computed> @ index.js:1
printWarning @ react-jsx-dev-runtime.development.js:117
error @ react-jsx-dev-runtime.development.js:93
validateExplicitKey @ react-jsx-dev-runtime.development.js:986
validateChildKeys @ react-jsx-dev-runtime.development.js:1013
jsxWithValidation @ react-jsx-dev-runtime.development.js:1174
ParticipantsView @ App.js:454
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
    at tr
    at table
    at div
    at ParticipantView (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:387:5)
    at div
    at div
    at ParticipantsView (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:761:82)
    at div
    at div
    at div
    at MeetingView (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1002:5)
    at MeetingProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:200049:23)
    at App (http://localhost:3000/react-rtc-demo/static/js/main.chunk.js:1442:83)
    at ThemeProvider (http://localhost:3000/react-rtc-demo/static/js/vendors~main.chunk.js:177330:24)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
validateDOMNesting @ react-dom.development.js:10081
createInstance @ react-dom.development.js:10181
completeWork @ react-dom.development.js:19464
completeUnitOfWork @ react-dom.development.js:22815
performUnitOfWork @ react-dom.development.js:22787
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
App.js:622  onEntryResponded qqrfpz7t allowed
App.js:634 onMeetingJoined
```

**Comment by ahmedbhesaniya97** [comment]
Hi @alejandrodavidmalavet,
Can you please raise an issue on our discord channel ?
https://discord.gg/ex7Pvtjcjz
